### ISSUE TITLE
Preprocessing doesn't work 

### ISSUE THREAD

**Issue by peihua-wang** [TheoryInPractice/practical-oct#1]
I run into this when using `python -m experiments.preprocessing.run`:

Identified 61 Huffner files
Processing aa10
Traceback (most recent call last):
    File "/Users/wangpeihua/anaconda3/envs/env_practical_oct/lib/python3.5/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
    File "/Users/wangpeihua/anaconda3/envs/env_practical_oct/lib/python3.5/runpy.py", line 85, in _run_code
        exec(code, run_globals)
    File "/Volumes/LaCie/practical-oct-master1/experiments/preprocessing/run.py", line 494, in <module>
        convert_huffner()
    File "/Volumes/LaCie/practical-oct-master1/experiments/preprocessing/run.py", line 100, in convert_huffner
        graph = read_huffner(original_dir / 'huffner', dataset)
    File "/Volumes/LaCie/practical-oct-master1/src/preprocessing/graphs.py", line 94, in read_huffner
        with open_path(input_dir / dataset_name, 'r') as infile:
    File "/Volumes/LaCie/practical-oct-master1/src/preprocessing/graphs.py", line 18, in open_path
        return open(str(path), mode)
FileNotFoundError: [Errno 2] No such file or directory: 'data/original/huffner/aa10'

Also for `python -m experiments.data.validate -precomputed synthetic_precomputed_0-14.csv`
Traceback (most recent call last):
  File "/Users/wangpeihua/anaconda3/envs/env_practical_oct/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/wangpeihua/anaconda3/envs/env_practical_oct/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Volumes/LaCie/practical-oct-master1/experiments/data/validate.py", line 57, in <module>
    csv_dir, 'synthetic_summary.csv', args.precomputed)
  File "/Volumes/LaCie/practical-oct-master1/experiments/data/validate.py", line 39, in _compare_to_ground_truth
    line1.strip(), line2.strip()))
ValueError: Lines didn't match: 'aa10-ba-15,69,198' and 'aa10-ba-0,69,198''

while `python -m experiments.data.sanitize` runs properly. 

In addition, may I know do I need to go through "Data (Quantum and Synthetic)"  (probably this is for quantum computing?) if I only need to find the smallest oct in my graph (300 nodes and 500 edges)? Thanks!

**Comment by tdgoodrich** [comment]
Hi @peihua-wang, can you confirm that you ran `make` and `make data` before trying `python -m experiments.preprocessing.run`?

Sidenote: I'm currently having problems with the virtualenv setup in our makefile on a fresh Macbook Pro (the numpy install crashes), we are digging into this further.

**Comment by peihua-wang** [comment]
Hi @tdgoodrich , glad to hear from you. Yes I ran `make` and `make data`.

**Comment by tdgoodrich** [comment]
Ah, I've found the issue. I'm rerunning on my end and will push the update soon.

To answer your second question: You only need to run the steps in `REPLICABILITY.md` if you're reproducing our experimental results. If you're just looking to compute an OCT set on your own graph, then the instructions from `README.md` will suffice. I recommend running the Akiba-Iwata solver or (if you have CPLEX installed), the ILP solver.

**Comment by peihua-wang** [comment]
Hi @tdgoodrich , thank you so much. I tried the Akiba-Iwata solver. It works for my small toy data while gives an empty certificate for my experiment data which does have an OCT.  I will try the ILP solver later.

**Comment by tdgoodrich** [comment]
Could you share the experiment data? I'm happy to try it on my end. It's possible that an empty certificate from Akiba-Iwata is a crash that's being suppressed.

**Comment by peihua-wang** [comment]
Sure! I will send it to you by email  ; )
